Repository EICPCohort5/capstone-project, pull requests merged in 2022-03, with the labels that each got.

#50 Pubspec YAML change
  .github/pr-labeler.yml
  documentation/spec.yaml
Labels: doc

#61 Merging Testing to Main
  documentation/spec.yaml
  sql/demoSchema.sql
Labels: testing

#69 Testing
  GITFLOW.md
  package.json
  test/BackEnd/BackEndTesting.js
  test/DataBases/DataBasesTesting.js
  test/DevSecOps/DevSecOpsTesting.js
  test/FrontEnd/FrontEndTesting.js
  test/TestingAndDocs/TestingAndDocsTesting.js
  test/testingIntegration.js
Labels: devsecops

#71 Front-end restructured
  orm/orm-folder-fill
  orm/tracking-model.js
  package.json
  public/images/images-folder-fill
  public/javascripts/js-folder-fill
  src/App.vue
  src/assets/stonecap.png
  src/components/FooterBar.vue
  src/components/Nav.vue
  src/components/NavBar.vue
  src/js/addCustomer.js
  src/js/addOrder.js
  src/js/dashboard.js
  src/js/editCustomer.js
  src/js/editOrder.js
  src/js/manageCustomers.js
  src/js/manageOrders.js
  src/js/products.js
  src/main.js
  src/router/index.js
  src/views/AddCustomer.vue
  src/views/AddOrder.vue
  src/views/DashBoard.vue
  src/views/EditCustomer.vue
  src/views/EditOrder.vue
  src/views/ManageCustomers.vue
  src/views/ManageOrders.vue
  src/views/ProductS.vue
Labels: devsecops

#72 Added backend npm starts
  package.json
Labels: devsecops

#73 Testing
  orm/orm-folder-fill
  orm/tracking-model.js
  package.json
  public/images/images-folder-fill
  public/javascripts/js-folder-fill
  src/App.vue
  src/assets/stonecap.png
  src/components/FooterBar.vue
  src/components/Nav.vue
  src/components/NavBar.vue
  src/js/addCustomer.js
  src/js/addOrder.js
  src/js/dashboard.js
  src/js/editCustomer.js
  src/js/editOrder.js
  src/js/manageCustomers.js
  src/js/manageOrders.js
  src/js/products.js
  src/main.js
  src/router/index.js
  src/views/AddCustomer.vue
  src/views/AddOrder.vue
  src/views/DashBoard.vue
  src/views/EditCustomer.vue
  src/views/EditOrder.vue
  src/views/ManageCustomers.vue
  src/views/ManageOrders.vue
  src/views/ProductS.vue
Labels: devsecops

#104 Backend_TestingToMain_BT
  app.js
  orm/Customer.js
  orm/Customers.js
  orm/db-connection.js
  orm/model-test/demo-model.js
  orm/tracking-model.js
  package.json
  routes/customers.js
  routes/index.js
  test/BackEnd/BackEndTesting.js
Labels: devsecops

#106 DOC: Minor changes to OpenAPI Documentation
  documentation/spec.yaml
Labels: devsecops

#107 Merging testing to main.
  documentation/spec.yaml
Labels: devsecops

#109 Front-end Work for the day on updating
  src/assets/body_bg.jpg
  src/assets/dashboard-background.png
  src/assets/navbar_icon/customer.png
  src/assets/navbar_icon/dashboard.png
  src/assets/navbar_icon/orders.png
  src/assets/navbar_icon/products.png
  src/assets/navbar_icon/profile.png
  src/components/Nav.vue
  src/components/NavBar.vue
  src/js/dashboard.js
  src/router/index.js
  src/views/AddCustomer.vue
  src/views/AddOrder.vue
  src/views/DashBoard.vue
  src/views/EditCustomer.vue
  src/views/EditOrder.vue
  src/views/ManageCustomers.vue
  src/views/ManageOrders.vue
  src/views/ProductS.vue
Labels: devsecops

#110 Testing
  src/assets/body_bg.jpg
  src/assets/dashboard-background.png
  src/assets/navbar_icon/customer.png
  src/assets/navbar_icon/dashboard.png
  src/assets/navbar_icon/orders.png
  src/assets/navbar_icon/products.png
  src/assets/navbar_icon/profile.png
  src/components/Nav.vue
  src/components/NavBar.vue
  src/js/dashboard.js
  src/router/index.js
  src/views/AddCustomer.vue
  src/views/AddOrder.vue
  src/views/DashBoard.vue
  src/views/EditCustomer.vue
  src/views/EditOrder.vue
  src/views/ManageCustomers.vue
  src/views/ManageOrders.vue
  src/views/ProductS.vue
Labels: devsecops

#123 Front end fixed sonar cloud
  src/js/manageCustomers.js
  src/views/DashBoard.vue
Labels: devsecops

#124 Back-End merge for Customer, Product API and DB connection changes
  app.js
  orm/Customer.js
  orm/Order.js
  orm/Product.js
  orm/Products.js
  orm/db-connection.js
  orm/tracking-model.js
  routes/customers.js
  routes/products.js
  sql/demoSchema.sql
  test/routes/customers.test.js
Labels: devsecops

#126 .gitignore edit
  .gitignore
Labels: devsecops

#127 Testing
  .gitignore
Labels: devsecops

#128 Config.js
  src/js/config.js
Labels: devsecops

#130 edited package.json
  package.json
Labels: devsecops

#133 Added Concurrently for npm start Front end
  package.json
Labels: devsecops

#136 Front end
  package.json
Labels: devsecops

#141 Steves Fix
  README.md
  documentation/spec.yml
  package.json
Labels: devsecops

#144 Front end
  package.json
  src/js/addCustomer.js
  src/views/EditCustomer.vue
  src/views/ManageCustomers.vue
Labels: devsecops

#146 Testing -> Main
  package.json
  src/js/addCustomer.js
  src/views/EditCustomer.vue
  src/views/ManageCustomers.vue
Labels: devsecops

#149 Remove concurrency module
  package.json
Labels: devsecops

#151 Testing -> main
  package.json
Labels: devsecops

#155 Reverting back to old changes
  package.json
Labels: devsecops

#160 Front end to testing with Hopefully Azure Solution
  .github/workflows/main_wadadawdawda.yml
  .gitignore
  app.js
  orm/Customer.js
  package.json
  src/js/addCustomer.js
  src/views/AddCustomer.vue
  src/views/EditCustomer.vue
Labels: devsecops

#161 Merge test -> main with Jun Hao
  .gitignore
  app.js
  orm/Customer.js
  package.json
  src/js/addCustomer.js
  src/views/AddCustomer.vue
  src/views/EditCustomer.vue
Labels: devsecops

#165 Front end
  src/js/addCustomer.js
  src/js/editCustomer.js
  src/js/manageCustomers.js
Labels: devsecops

#166 DB connection string update for Azure
  orm/Order.js
  orm/OrderProduct.js
  orm/OrderStatusCode.js
  orm/db-connection.js
  orm/tracking-model.js
Labels: devsecops

#167 Testing -> main to fix database connection issue
  orm/Order.js
  orm/OrderProduct.js
  orm/OrderStatusCode.js
  orm/db-connection.js
  orm/tracking-model.js
  src/js/addCustomer.js
  src/js/editCustomer.js
  src/js/manageCustomers.js
Labels: devsecops

#168 TEST: Added UT and IT for addCustomers, manageCustomers
  package.json
  src/js/addCustomer.js
  test/DevSecOpsTesting.js
  test/Integration.js
  test/src/js/addCustomer.test.js
  test/src/js/index.test.js
  test/src/js/manageCustomers.test.js
Labels: devsecops

#170 Made Db Changes
  orm/db-connection.js
  src/js/addCustomer.js
  src/js/editCustomer.js
  src/js/manageCustomers.js
Labels: devsecops

#173 fixed if statement
  orm/db-connection.js
Labels: devsecops

#178 Front end work
  public/favicon.ico
  src/App.vue
  src/components/NavBar.vue
  src/js/addCustomer.js
  src/js/addOrder.js
  src/js/editCustomer.js
  src/js/editOrder.js
  src/js/login.js
  src/js/manageCustomers.js
  src/js/manageOrders.js
  src/js/products.js
  src/router/index.js
  src/views/DashBoard.vue
  src/views/ManageCustomers.vue
  src/views/ManageOrders.vue
Labels: devsecops

#179 Testing -> Main to fix API
  public/favicon.ico
  src/App.vue
  src/components/NavBar.vue
  src/js/addCustomer.js
  src/js/addOrder.js
  src/js/editCustomer.js
  src/js/editOrder.js
  src/js/login.js
  src/js/manageCustomers.js
  src/js/manageOrders.js
  src/js/products.js
  src/router/index.js
  src/views/DashBoard.vue
  src/views/ManageCustomers.vue
  src/views/ManageOrders.vue
Labels: devsecops

#181 Back-end Order API foundations
  orm/tracking-model.js
  package.json
  routes/customers.js
  routes/orders.js
  routes/products.js
  test/routes/customers.test.js
  test/routes/products.test.js
Labels: devsecops

#182 Testing -> Main with Backend
  orm/tracking-model.js
  package.json
  routes/customers.js
  routes/orders.js
  routes/products.js
  test/routes/customers.test.js
  test/routes/products.test.js
Labels: devsecops

#188 JWT Authentication + country field fix w unit tests
  app.js
  orm/db-connection.js
  orm/tracking-model.js
  package.json
  routes/customers.js
  routes/orders.js
  routes/products.js
  routes/tokenValidator.js
  sql/demoSchema.sql
  test/app.test.js
  test/routes/customers.test.js
  test/routes/orders.test.js
  test/routes/products.test.js
Labels: devsecops

#189 Testing -> Main with backend code
  app.js
  orm/db-connection.js
  orm/tracking-model.js
  package.json
  routes/customers.js
  routes/orders.js
  routes/products.js
  routes/tokenValidator.js
  sql/demoSchema.sql
  test/app.test.js
  test/routes/customers.test.js
  test/routes/orders.test.js
  test/routes/products.test.js
Labels: devsecops

#194 Front end LOGIN implementation
  app.js
  src/components/NavBar.vue
  src/js/addCustomer.js
  src/js/detailCustomer.js
  src/js/detailOrder.js
  src/js/editCustomer.js
  src/js/login.js
  src/js/manageCustomers.js
  src/js/manageOrders.js
  src/main.js
  src/views/EditCustomer.vue
  src/views/LogIn.vue
Labels: devsecops

#195 Testing -> main for front end to fix login page
  app.js
  src/components/NavBar.vue
  src/js/addCustomer.js
  src/js/detailCustomer.js
  src/js/detailOrder.js
  src/js/editCustomer.js
  src/js/login.js
  src/js/manageCustomers.js
  src/js/manageOrders.js
  src/main.js
  src/views/EditCustomer.vue
  src/views/LogIn.vue
Labels: devsecops

#197 Front end fixed some console errors on prod
  src/js/login.js
  src/views/AddCustomer.vue
  src/views/AddOrder.vue
  src/views/DetailCustomer.vue
  src/views/DetailOrder.vue
  src/views/EditCustomer.vue
  src/views/EditOrder.vue
Labels: devsecops

#199 API crash + Customer address validation fixes
  routes/customers.js
  routes/orders.js
  routes/products.js
Labels: devsecops

#201 Testing -> Main with Backend Changes/Fixes
  README.md
  routes/customers.js
  routes/orders.js
  routes/products.js
  src/js/login.js
  src/views/AddCustomer.vue
  src/views/AddOrder.vue
  src/views/DetailCustomer.vue
  src/views/DetailOrder.vue
  src/views/EditCustomer.vue
  src/views/EditOrder.vue
Labels: devsecops

#203 Customer and Order associations for GET calls
  orm/tracking-model.js
  routes/customers.js
  routes/orders.js
Labels: devsecops

#204 Testing
  orm/tracking-model.js
  routes/customers.js
  routes/orders.js
Labels: devsecops

#206 Customer middlename validation fix
  routes/customers.js
Labels: devsecops

#211 Testing -> Main Front end & Back End
  routes/customers.js
  src/App.vue
  src/js/addCustomer.js
  src/js/addOrder.js
  src/js/detailCustomer.js
  src/js/detailOrder.js
  src/js/editCustomer.js
  src/js/editOrder.js
  src/js/manageCustomers.js
  src/js/manageOrders.js
  src/js/products.js
  src/router/index.js
  src/views/AddCustomer.vue
  src/views/AddOrder.vue
  src/views/DashBoard.vue
  src/views/DetailCustomer.vue
  src/views/DetailOrder.vue
  src/views/EditCustomer.vue
  src/views/EditOrder.vue
  src/views/ManageCustomers.vue
  src/views/ManageOrders.vue
  src/views/ProductS.vue
Labels: devsecops

#214 Testing -> Main
  orm/tracking-model.js
  routes/orders.js
Labels: devsecops

#217 Testing -> Main
  src/js/addCustomer.js
  src/js/editCustomer.js
Labels: devsecops

#219 Front end
  src/js/manageOrders.js
  src/views/ManageOrders.vue
Labels: devsecops

#220 Testing -> Main
  src/js/manageOrders.js
  src/views/ManageOrders.vue
Labels: devsecops
